.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "MASALA" "1" "April 2013" "" ""
.
.SH "NAME"
\fBmasala\fR \- P2P name resolution daemon
.
.SH "SYNOPSIS"
\fBmasala\fR [\-d] [\-q] [\-h hostname] [\-k password] [\-r realm] [\-p port] [\-ba server] [\-bp port] [\-u username]
.
.SH "DESCRIPTION"
\fBmasala\fR is a P2P name resolution daemon\. It organizes IPv6 addresses in a distributed hash table\. The basic design has been inspired by the Kademlia DHT\. The communication between nodes is realized by using bencode encoded messages on top of UDP\. There are 4 message types: PING, FIND, LOOKUP and ANNOUNCE\. By default, masala sends the first packet to a multicast address\. So there is no configuration necessary within your broadcast domain (LAN) and will continue to do so in intervals until another node is found\. With a bootstrap server, it is also possible to connect nodes around the globe\. Masala also includes a very simple DNS server so it can be used as a local upstream DNS server\.
.
.SH "OPTIONS"
.
.TP
\fB\-h, \-\-hostname\fR \fIhostname\fR
By default /etc/hostname is used to determine the hostname\.
.
.TP
\fB\-k, \-\-key\fR \fIpassword\fR
Setting a password results in encrypting each packet with AES256\. The encrypted packet is encapsulated in bencode\. With this action you effectively isolate your nodes from the rest of the world\.
.
.TP
\fB\-r, \-\-realm\fR \fIrealm\fR
Creating a realm affects the lookup process and the way how you announce your hostname to the swarm\. It helps you to isolate your nodes and be part of a bigger swarm at the same time\. This can be useful if you do not have your own bootstrap server and do not want to get mixed up with the rest of the swarm\. You do not have problems with duplicate hostnames either as long as you do not share your realm with others\.
.
.TP
\fB\-p, \-\-port\fR \fIport\fR
Listen to this port (Default: UDP/8337)
.
.TP
\fB\-ba, \-\-bootstrap\-addr\fR \fIserver\fR
Use server as a bootstrap server\. The server can be an IPv6 address, a FQHN like www\.example\.net or even a IPv6 multicast address\. (Default: ff0e::1)
.
.TP
\fB\-bp, \-\-bootstrap\-port\fR \fIport\fR
The bootstrap server will be addressed at this port\. (Default: UDP/8337)
.
.TP
\fB\-u, \-\-user\fR \fIusername\fR
When starting as root, use \-u to change the UID\.
.
.TP
\fB\-d, \-\-daemon\fR
Start as a daemon and run in background\. The output will be send to syslog\.
.
.TP
\fB\-q, \-\-quiet\fR
Be quiet and do not log anything\.
.
.TP
\fB\-\-help\fR
Show a summary of all available command line parameters\.
.
.TP
\fB\-da, \-\-dns\-addr\fR
Bind the DNS server interface to this address (Default: ::1)\.
.
.TP
\fB\-dp, \-\-dns\-port\fR
Bind the DNS server interface to this port (Default: 3444)\.
.
.TP
\fB\-di, \-\-dns\-ifce\fR
Bind the DNS server interface to this interface (Default: <any>)\.
.
.SH "EXAMPLES"
Announce the hostname \fIfubar\.p2p\fR with the encryption password \fIfubar\fR:
.
.IP "" 4
.
.nf

$ masala \-h fubar\.p2p \-k fubar
.
.fi
.
.IP "" 0
.
.SH "BUGS"
Lack of IPv6 support by the providers\.
